name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - run: uv sync --group dev --no-default-groups --python=${{ matrix.python-version }}
      - run: uv run pytest --cov --disable-warnings
      - name: Upload coverage report to codecov
        if: ${{ matrix.python-version == '3.14' }}
        uses: codecov/codecov-action@v5
